#define TYPE_AMD_VIOMMU_PCI "AMD-VIOMMU-PCI"
#define AMD_VIOMMU_PCI(obj)\
    OBJECT_CHECK(AMDVIPCIState, (obj), TYPE_AMD_VIOMMU_PCI)

#define TYPE_AMD_VIOMMU_DEVICE "amd-viommu"
#define AMD_VIOMMU_DEVICE(obj)\
    OBJECT_CHECK(AMDVIState, (obj), TYPE_AMD_VIOMMU_DEVICE)

#define TYPE_AMD_VIOMMU_MEMORY_REGION "amd-viommu-memory-region"

#define SUPPORTED_EFR   (AMDVI_FEATURE_PPR | AMDVI_FEATURE_XT | \
                          AMDVI_FEATURE_GT | AMDVI_FEATURE_GA | \
                          AMDVI_FEATURE_GIO | AMDVI_FEATURE_EPHSUP | AMDVI_FEATURE_GATS_5LEVEL | \
                          AMDVI_FEATURE_GLX_2LEVEL | AMDVI_FEATURE_PASMAX_16)

/* default extended feature */
#define AMD_VIOMMU_DEFAULT_EXT_FEATURES \
        (AMDVI_FEATURE_PREFETCH | AMDVI_FEATURE_PPR | \
        AMDVI_FEATURE_IA | AMDVI_FEATURE_GT | AMDVI_FEATURE_HE | \
        AMDVI_GATS_MODE | AMDVI_HATS_MODE | AMDVI_FEATURE_GA)

/* capabilities header */
#define AMD_VIOMMU_CAPAB_FEATURES (AMDVI_CAPAB_FLAT_EXT | \
        AMDVI_CAPAB_FLAG_IOTLBSUP | \
        AMDVI_CAPAB_ID_SEC | AMDVI_CAPAB_INIT_TYPE | \
        AMDVI_CAPAB_FLAG_HTTUNNEL |  AMDVI_CAPAB_EFR_SUP)

